all:
  children:
    homelab:
      vars:
        ansible_user: root
        ansible_ssh_private_key_file: ~/.ssh/id_rsa_homelab
      
      hosts:
        goliath.net.bois.vt:
          ansible_host: goliath.net.bois.vt

        mysql.net.bois.vt:
          ansible_host: mysql.net.bois.vt
        
        mysql-backup.net.bois.vt:
          ansible_host: mysql-backup.net.bois.vt
        
        hl2dm-server.net.bois.vt:
          ansible_host: hl2dm-server.net.bois.vt

        calibre-server.net.bois.vt:
          ansible_host: calibre-server.net.bois.vt

        agd-darkweb.net.bois.vt:
          ansible_host: agb-darkweb.net.bois.vt

        invidious.net.bois.vt:
          ansible_host: invidious.net.bois.vt

        openvpn.net.bois.vt:
          ansible_host: openvpn.net.bois.vt
