all:
  children:
    homelab:
      vars:
        ansible_user: root
        ansible_ssh_private_key_file: ~/.ssh/id_rsa_homelab
      
      hosts:
        hubby.internal:
          ansible_host: hubby.internal
          ansible_user: damien
                    
        goliath.internal:
          ansible_host: goliath.internal

        mysql.internal:
          ansible_host: mysql.internal
        
        mysql-backup.internal:
          ansible_host: mysql-backup.internal
        
        hl2dm-server.internal:
          ansible_host: hl2dm-server.internal

        calibre-server.internal:
          ansible_host: calibre-server.internal

        agd-darkweb.internal:
          ansible_host: agb-darkweb.internal

        invidious.internal:
          ansible_host: 10.0.0.138

        openvpn.internal:
          ansible_host: openvpn.internal

    arch_live:
      vars:
        ansible_user: root
        # disable host key checking
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
      hosts:
        archiso:
          ansible_host: 10.0.0.212
    penguin:
      vars:
        ansible_user: root
      hosts:
        ben.per.bois.vt:
          ansible_host: ben.per.bois.vt
        twingate-connector.per.bois.vt:
          ansible_host: 10.133.128.7
        munin.per.bois.vt:
          ansible_host: 10.133.128.8

    robotics-onboard-pis:
      vars:
        ansible_user: penguin
        ansible_ssh_private_key_file: ~/.ssh/id_rsa_penguin
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
      
      hosts:
        cedar.lan:
          ansible_host: cedar.lan
        amber.lan: # yes mel it's a you reference
          ansible_host: amber.lan