all:
  children:
    homelab:
      vars:
        ansible_user: root
        ansible_ssh_private_key_file: ~/.ssh/id_rsa_homelab
      hosts:
        goliath.bois.vt:
          ansible_host: goliath.bois.vt

        mysql.bois.vt:
          ansible_host: mysql.internal
        
        mysql-backup.bois.vt:
          ansible_host: mysql-backup.internal