all:
  children:
    homelab:
      vars:
        ansible_user: root
        ansible_ssh_private_key_file: ~/.ssh/id_rsa_homelab
      
      hosts:
        goliath.internal:
          ansible_host: goliath.internal

        mysql.internal:
          ansible_host: mysql.internal
        
        mysql-backup.internal:
          ansible_host: mysql-backup.internal
        
        hl2dm-server.internal:
          ansible_host: hl2dm-server.internal

        calibre-server.internal:
          ansible_host: calibre-server.internal

        agd-darkweb.internal:
          ansible_host: agb-darkweb.internal

        invidious.internal:
          ansible_host: 10.0.0.138

        openvpn.internal:
          ansible_host: openvpn.internal
