---
- name: Install Arch Linux with KDE Plasma
  hosts: arch_live
  become: true
  tasks:
    - name: Partition the disk
      tags:
        - partition
      shell: |
        parted -s {{ disk }} mklabel gpt
        parted -s {{ disk }} mkpart ESP fat32 1MiB 513MiB
        parted -s {{ disk }} set 1 esp on
        parted -s {{ disk }} mkpart primary ext4 513MiB 100%

    - name: Format the partitions
      tags:
        - format
      shell: |
        mkfs.fat -F32 -n EFI {{ disk }}p1
        mkfs.ext4 {{ disk }}p2

    - name: Mount the partitions
      tags:
        - mount
      shell: |
        mount {{ disk }}p2 /mnt
        mkdir -p /mnt/boot
        mount {{ disk }}p1 /mnt/boot

    - name: Install base system
      tags:
        - install_base
      shell: |
        pacstrap /mnt {{ core_system | join(' ') }}

    - name: Generate fstab
      tags:
        - fstab
      shell: |
        genfstab -U /mnt >> /mnt/etc/fstab

    - name: Configure chroot environment
      tags:
        - chroot
      copy:
        content: |
          ln -sf /usr/share/zoneinfo/{{ timezone }} /etc/localtime
          hwclock --systohc
          # echo "{{ locale }}" > /etc/locale.gen
          locale-gen
          echo "LANG={{ locale }}" > /etc/locale.conf
          echo "{{ hostname }}" > /etc/hostname
          echo "127.0.0.1 localhost" >> /etc/hosts
          echo "::1       localhost" >> /etc/hosts
          echo "127.0.1.1 {{ hostname }}.localdomain {{ hostname }}" >> /etc/hosts
          echo -e "{{ root_password }}\n{{ root_password }}" | passwd root
          systemctl enable NetworkManager

        dest: /mnt/root/setup.sh
        mode: "0755"

    - name: Run chroot setup script
      tags:
        - run_chroot
      shell: arch-chroot /mnt /root/setup.sh

    - name: Create user
      tags:
        - create_user
      shell: |
        arch-chroot /mnt useradd -m -G wheel -s /bin/bash {{ username }}
        echo -e "{{ user_password }}\n{{ user_password }}" | arch-chroot /mnt passwd {{ username }}
        echo "%wheel ALL=(ALL) ALL" >> /mnt/etc/sudoers

    - name: Install Desktop Environment
      tags:
        - install_de
      shell: |
        arch-chroot /mnt pacman -Sy --noconfirm {{ de | join(' ') }}
    
    - name: Install additional packages
      tags:
        - install_packages
      command: arch-chroot /mnt pacman -S {{ item }}
      loop: "{{ custom }}"

    - name: Install GRUB and required packages
      tags:
        - install_grub
      shell: |
        arch-chroot /mnt pacman -Sy --noconfirm grub efibootmgr os-prober

    - name: Install GRUB bootloader
      tags:
        - grub_bootloader
      shell: |
        arch-chroot /mnt grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB

    - name: Generate GRUB config
      tags:
        - grub_config
      shell: |
        arch-chroot /mnt grub-mkconfig -o /boot/grub/grub.cfg

    - name: Clean up
      tags:
        - cleanup
      shell: |
        umount -R /mnt
