---
- name: Add SSH key
  hosts: all
  become: yes
  tasks:
    - name: Add SSH key to authorized_keys
      authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa_homelab.pub') }}"